name: Java CI and Publish with Maven
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'
    - name: build
      run: |
        ./mvnw -B package
    - name: Publish generated content to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.5
      with:
        branch: gh-pages
        folder: SparkBuilderGeneratorUpdateSite/target/repository

